### ISSUE TITLE
Need Some Java Programs(See Descriptions)

### ISSUE THREAD

**Issue by YaminiShrestha31** [YaminiShrestha31/Java-LecturesNotes#1]
### **Programs**

- Printing Pattern

- Factorial

- Sorting
etc.....

**Comment by codetravellearn** [comment]
I CAN DO THIS

**Comment by YaminiShrestha31** [comment]
These issues are open to all..

**Comment by pratu098** [comment]
Can we directly make pull request?

**Comment by parjanyaacoder** [comment]
I would like to work on this issue. @YaminiShrestha31

**Comment by Vaibhav22-Dev** [comment]
hello, I would like to contribute ,Is someone help me how to start. I am unable to fork repository it is saying only member can fork it
